### ISSUE TITLE
npm i unable to resolve dependency tree web@0.1.0 in React ^17.0.1

### ISSUE THREAD

**Issue by teletobbie** [jsdevkr/react-multi-email#67]
I am trying to install this package, but I am getting a npm error:

npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: web@0.1.0
npm ERR! Found: react@17.0.2
npm ERR! node_modules/react
npm ERR!   react@"^17.0.1" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^16.3.2" from react-multi-email@0.5.3
npm ERR! node_modules/react-multi-email
npm ERR!   react-multi-email@"*" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /root/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-05-26T12_35_14_003Z-debug.log

Has this the do with the older react version (16.3.2) versus my react version ^17.0.1? And if so how can I fix it?

**Comment by cbothra** [comment]
Hi, I also ran into the same issue. Though it worked for now using `--legacy-peer-deps` but please update the react version to get rid of this warning/error. 

Thanks-in-advance.
