### ISSUE TITLE
Default options override specific options

### ISSUE THREAD

**Issue by tuhlmann** [jsdevkr/react-multi-email#8]
Just found the order of options is wrong in places like https://github.com/jsdevkr/react-multi-email/blob/master/src/react-multi-email/isEmail.tsx#L92

It should instead read `options = { ...defaultEmailOptions, ...options }`, the rightmost value wins.
This would apply for `isFQDN` as well.

Thanks for creating this useful component! I did modify it a bit to enable email addresses with display names when I ran into this issue.

**Comment by tuhlmann** [comment]
@JeonHyungJin Thanks for tackling it. Let me know if you need some help.

**Comment by thomasJang** [comment]
@JeonHyungJin 
It is a very simple matter, you just need to change the typing order. Maybe this documentation helps to you (https://developer.mozilla.org/ko/docs/Web/JavaScript/Reference/Operators/Spread_syntax)

**Comment by NamJinWoo** [comment]
I just changed the typing order of options.
If another problem happens, please let me know.

Thanks!

**Comment by thomasJang** [comment]
You need to change `function isEmail` too

**Comment by NamJinWoo** [comment]
@thomasJang I will take care of it
